version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: PracticeGrading.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=postgres;Database=postgres;Username=postgres;Password=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./PracticeGrading.Data/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
      - ./pg-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api:5001
    depends_on:
      - api