services:
  api:
    build:
      context: .
      dockerfile: PracticeGrading.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=postgres;Database=practice_grading;Username=postgres;Password=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: practice_grading
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
      timeout: 5s
    volumes:
      - ./PracticeGrading.Data/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
      - ./pg-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - api