-- Новые поля студенческих работ.
ALTER TABLE "StudentWork"
    ADD COLUMN "SupervisorInfo" text,
    ADD COLUMN "ReviewerInfo" text;

-- Новые поля пользователей.
ALTER TABLE "Users"
    ADD COLUMN "Email" text,
    ADD COLUMN "Phone" text,
    ADD COLUMN "InformationRu" text,
    ADD COLUMN "InformationEn" text;

-- Новая связь многие-ко-многим между встречами и участниками.
CREATE TABLE "MeetingUser" (
    "MeetingsId" integer NOT NULL,
    "MembersId" integer NOT NULL,

    CONSTRAINT "PK_MeetingUser"
        PRIMARY KEY ("MeetingsId", "MembersId"),

    CONSTRAINT "FK_MeetingUser_Meetings_MeetingsId"
        FOREIGN KEY ("MeetingsId")
        REFERENCES "Meetings" ("Id")
        ON DELETE CASCADE,

    CONSTRAINT "FK_MeetingUser_Users_MembersId"
        FOREIGN KEY ("MembersId")
        REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

-- Сохраняем существующие связи до удаления Users.MeetingId.
INSERT INTO "MeetingUser" ("MeetingsId", "MembersId")
SELECT "MeetingId", "Id"
FROM "Users"
WHERE "MeetingId" IS NOT NULL;

-- Проверяем, что все старые связи перенесены.
DO $$
DECLARE
    old_relation_count integer;
    new_relation_count integer;
BEGIN
    SELECT count(*)
    INTO old_relation_count
    FROM "Users"
    WHERE "MeetingId" IS NOT NULL;

    SELECT count(*)
    INTO new_relation_count
    FROM "MeetingUser";

    IF old_relation_count <> new_relation_count THEN
        RAISE EXCEPTION
            'Meeting relations were not transferred: old=%, new=%',
            old_relation_count,
            new_relation_count;
    END IF;
END;
$$;

-- Старую связь удаляем только после успешного переноса.
ALTER TABLE "Users"
    DROP CONSTRAINT "FK_Users_Meetings_MeetingId";

DROP INDEX "IX_Users_MeetingId";

ALTER TABLE "Users"
    DROP COLUMN "MeetingId";

CREATE INDEX "IX_MeetingUser_MembersId"
    ON "MeetingUser" ("MembersId");

-- Персональный доступ участника к конкретной встрече.
CREATE TABLE "MeetingMemberAccesses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MeetingId" integer NOT NULL,
    "MemberId" integer NOT NULL,
    "TokenHash" character varying(64) NOT NULL,
    "Status" integer DEFAULT 0 NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "StatusChangedAt" timestamp with time zone,
    "StatusChangedByUserId" integer,

    CONSTRAINT "PK_MeetingMemberAccesses"
        PRIMARY KEY ("Id"),

    CONSTRAINT "CK_MeetingMemberAccesses_Status"
        CHECK ("Status" >= 0 AND "Status" <= 3),

    CONSTRAINT "FK_MeetingMemberAccesses_Meetings_MeetingId"
        FOREIGN KEY ("MeetingId")
        REFERENCES "Meetings" ("Id")
        ON DELETE CASCADE,

    CONSTRAINT "FK_MeetingMemberAccesses_Users_MemberId"
        FOREIGN KEY ("MemberId")
        REFERENCES "Users" ("Id")
        ON DELETE CASCADE,

    CONSTRAINT "FK_MeetingMemberAccesses_Users_StatusChangedByUserId"
        FOREIGN KEY ("StatusChangedByUserId")
        REFERENCES "Users" ("Id")
        ON DELETE SET NULL
);

CREATE UNIQUE INDEX "IX_MeetingMemberAccesses_TokenHash"
    ON "MeetingMemberAccesses" ("TokenHash");

CREATE INDEX "IX_MeetingMemberAccesses_MemberId"
    ON "MeetingMemberAccesses" ("MemberId");

CREATE INDEX "IX_MeetingMemberAccesses_MeetingId_Status"
    ON "MeetingMemberAccesses" ("MeetingId", "Status");

CREATE INDEX "IX_MeetingMemberAccesses_StatusChangedByUserId"
    ON "MeetingMemberAccesses" ("StatusChangedByUserId");

-- Постоянный доверенный доступ участника.
CREATE TABLE "TrustedMemberAccesses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MemberId" integer NOT NULL,
    "TokenHash" character varying(64) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,

    CONSTRAINT "PK_TrustedMemberAccesses"
        PRIMARY KEY ("Id"),

    CONSTRAINT "FK_TrustedMemberAccesses_Users_MemberId"
        FOREIGN KEY ("MemberId")
        REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_TrustedMemberAccesses_MemberId"
    ON "TrustedMemberAccesses" ("MemberId");

CREATE UNIQUE INDEX "IX_TrustedMemberAccesses_TokenHash"
    ON "TrustedMemberAccesses" ("TokenHash");
