name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build

      - name: Tests
        run: dotnet test

      - name: Dotnet format
        run: dotnet format

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 5

      - name: Install dependencies and run Playwright tests
        run: |
          cd frontend
          npm ci
          npx playwright install --with-deps
          npx playwright test

      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.yml down