name: CI

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up PostgreSQL (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "CREATE DATABASE practice_grading;"
          sudo -u postgres psql -d practice_grading -f ./PracticeGrading.Data/init_database.sql

      - name: Set up PostgreSQL (Windows)
        if: runner.os == 'Windows'
        run: |
          pg_ctl start -D "C:\\Program Files\\PostgreSQL\\14\\data"
          psql -U postgres -c "CREATE DATABASE practice_grading;"
          psql -U postgres -d practice_grading -f ./PracticeGrading.Data/init_database.sql

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build

      - name: Tests
        run: dotnet test

      - name: Dotnet format
        run: dotnet format

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test